spring.application.name=TelegramWeatherBot
bot.token=${BOT_TOKEN}
weather.api.key=${WEATHER_API_KEY}
server.port=${PORT:8080}
spring.main.banner-mode=off

spring.datasource.url=jdbc:postgresql://localhost:5432/weather_bot_db
spring.datasource.username=postgres
spring.datasource.password=3479
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true